PADV - 317 - Creating a Composite Action
Pearson-Advance/tutor-build-image-action pull request #1
Opened 2023-02-16 20:47 UTC by sergivalero20

## Ticket

https://agile-jira.pearson.com/browse/PADV-317

## Description

This PR aims to create a composite action to build and push tutor image to Docker Hub.

## Type of Change

- Adding action that contains steps to build and push tutor image.

## Proof Of Concept

This is a POC, so the important to see or assess in this PR are each step in the workflow.

## Screenshot

This screenshot shows the result of the last execution of the workflow.

![image](https://user-images.githubusercontent.com/73655023/219482766-f9278b4a-b943-4736-bd48-50583b6873ac.png)

## Reviewers

- [ ] @anfbermudezme
- [ ] @Jacatove
- [ ] @Squirrel18

2023-02-17 02:49 UTC, Squirrel18 requested changes

2023-02-17 02:49 UTC, Squirrel18 commented on action.yml
> +    default: '15'
Tutor uses semantic versioning, so I think is better to use the full version name, in this case: 15.3.0. @sergivalero20

2023-02-17 02:49 UTC, Squirrel18 commented on action.yml
> +    description: 'The version of Tutor'
Could you add more details to this description? @sergivalero20

2023-02-17 02:49 UTC, Squirrel18 commented on action.yml
> +    description: 'The name of the repository'
Please, add as much information as you can. @sergivalero20

2023-02-17 02:49 UTC, Squirrel18 commented on action.yml
> +inputs:
We need a field to pass the name of the image we want to build, openedx, ecommerce, mfes... Without this field, we should not proceed. @sergivalero20

2023-02-17 02:49 UTC, Squirrel18 commented on action.yml
> +      shell: bash
Missing end of file line. @sergivalero20

2023-02-17 03:03 UTC, sergivalero20 commented on action.yml
> +    description: 'The version of Tutor'
Yes, sure!

2023-02-17 04:05 UTC, sergivalero20 commented on action.yml
> +    description: 'The name of the repository'
Ok, got it.

2023-02-17 04:25 UTC, sergivalero20 commented on action.yml
> +inputs:
Ok, got it.

2023-02-17 11:30 UTC, anfbermudezme commented on action.yml
> +    default: openedx
Shouldn't it be `edxops`? I say this because edxops is much more organized in terms of the name of the tags and our images of olive came from there https://hub.docker.com/r/edxops/edxapp/tags. Could you please review it?

2023-02-17 11:31 UTC, anfbermudezme commented
Could you please add context of the repository in the `README` like the information provided in this PR?

2023-02-17 12:44 UTC, sergivalero20 commented on action.yml
> +    default: openedx
Yes, It should be. During the test, I pushed the image to another repository, but I'm going to change it right now. Thanks @anfbermudezme

2023-02-17 19:29 UTC, sergivalero20 commented
@anfbermudezme Recently I add more specifications to README.md file.

2023-02-17 19:30 UTC, anfbermudezme commented on action.yml
> +    default: openedx
Get it, thanks.

2023-02-20 14:30 UTC, anfbermudezme commented
Could you please add in the PR description, how do you test the actions here https://github.com/Pearson-Advance/edx-platform/actions/runs/4197614288/jobs/7280163513 ?

2023-02-20 14:53 UTC, Jacatove requested changes

2023-02-20 14:53 UTC, Jacatove commented on action.yml
> +    description: 'This input refers the version of Python. It is useful since venv will be created from it.'
```suggestion
    description: 'Version of Python. It is useful since venv will be created from it.'
```

2023-02-20 14:53 UTC, Jacatove commented on action.yml
> +    description: 'This input refers the version of Tutor to be installed. It takes 15.3.0 by default.'
```suggestion
    description: 'Tutor version to be installed. It takes 15.3.0 by default.'
```

2023-02-20 14:53 UTC, Jacatove commented on action.yml
> +    description: 'This input refers the name of the repository already created in Docker Hub.'
```suggestion
    description: 'Name of the repository in Docker Hub.'
```

2023-02-20 14:53 UTC, Jacatove commented on action.yml
> +    description: 'This input refers username of the user created in Docker Hub.'
```suggestion
    description: 'Docker Hub username.'
```

2023-02-20 14:53 UTC, Jacatove commented on action.yml
> +    description: 'This input refers password of the user created in Docker Hub.'
```suggestion
    description: 'Docker Hub password.'
```

2023-02-20 14:53 UTC, Jacatove commented on action.yml
> +    default: openedx
I think there should not be default at all, it must be always specified,  mustn't it?.
```suggestion
  image-to-be-built:
    description: 'Image to be built.'
    required: true
```
@sergivalero20

2023-02-20 14:53 UTC, Jacatove commented on action.yml
> +    default: openedx
@sergivalero20 @anfbermudezme 
We can use a custom image name. The default is `tutor config printvalue DOCKER_IMAGE_OPENEDX`, however you can change it as well. https://docs.tutor.overhang.io/configuration.html#custom-images

2023-02-20 14:53 UTC, Jacatove commented on action.yml
> +    description: 'This input refers the tag of the image that will be pushed to Docker Hub. It assigns latest by default.'
```suggestion
    description: 'Tag of the image that will be pushed to Docker Hub. It assigns latest by default.'
```

2023-02-20 15:53 UTC, sergivalero20 commented on action.yml
> +        password: ${{ inputs.password }}
Yes, It's already using a token. I think the name of the input is wrong, I'll change it.

2023-02-20 16:01 UTC, sergivalero20 commented on action.yml
> +    default: openedx
Yes, your'e right!

2023-02-20 16:42 UTC, sergivalero20 commented
@anfbermudezme I already added about how to test the Composite Action from another repository.

2023-02-20 16:54 UTC, anfbermudezme requested changes

2023-02-20 16:54 UTC, anfbermudezme commented on action.yml
> +  username:
As @Squirrel18 mentioned, it's better to call this `docker-username`.

2023-02-20 16:54 UTC, anfbermudezme commented on action.yml
> +  token:
The same for this `docker-token`.

2023-02-20 16:54 UTC, anfbermudezme commented on action.yml
> +        username: ${{ inputs.username }}
Applying the suggestions before this needs to change.

2023-02-20 17:00 UTC, sergivalero20 commented on action.yml
> +  username:
Sorry, I forgot it.

2023-02-20 17:01 UTC, sergivalero20 commented on action.yml
> +        username: ${{ inputs.username }}
Changes applied!
Thanks @anfbermudezme for notify me.

2023-02-20 17:02 UTC, anfbermudezme approved these changes

2023-02-20 17:12 UTC, Squirrel18 approved these changes

2023-02-20 17:13 UTC, Jacatove approved these changes

2023-02-20 17:46 UTC, merged