PADV 327 - Add steps to install extra private requirements
Pearson-Advance/tutor-build-image-action pull request #3
Opened 2023-03-01 07:11 UTC by sergivalero20

## Ticket

https://agile-jira.pearson.com/browse/PADV-327

## Description

This PR adds two new step to the workflow that helps to install extra private requirements.

## Type of Change

- Adding two new steps to the workflow.

## Proof of Concept

This is a PoC, so the important to see or evaluate in this PR is each step in the workflow.

## How to test

- There is a branch called `vue/PADV-317` in openedx-platform that just contains one workflow. That workflow uses this Composite Action.
- There is a repository (only for test) created in Docker Hub called `pearsonopenedxops/tutor-test`.
- The workflow is activated when it push a commit to the `vue/PADV-317` branch.
- It is recommend to activate the workflow making a minor change on the code, for example change the tag of the image.

## Screenshot

The screenshot below shows the result of the last execution of the workflow.

![image](https://user-images.githubusercontent.com/73655023/222067674-ec65e99d-31db-46ad-8fc8-4a8255659c92.png)

## Reviewers

- [ ] @anfbermudezme
- [ ] @Jacatove
- [ ] @Squirrel18
- [ ]  @alexjmpb

2023-03-01 13:02 UTC, Jacatove commented on action.yml
> +    default: 'false'
shouldn't it be `false`?. @sergivalero20 
```suggestion
    default: false
```

2023-03-01 13:04 UTC, Jacatove commented on action.yml
> +    - if: ${{ inputs.theme-repository != 'false' }}
Maybe you can change the default to `""`,  the conditional becomes:
```suggestion
    - if: ${{ inputs.theme-repository != '' }}
```
@sergivalero20

2023-03-01 14:37 UTC, Squirrel18 requested changes

2023-03-01 14:37 UTC, Squirrel18 commented on action.yml
> +        repositories=("pearson-core")
This is just a POC, no need to add more packages. @Jacatove 
You need to get the list of private repositories from an environment variable: https://docs.github.com/en/actions/learn-github-actions/contexts#vars-context @sergivalero20

2023-03-01 14:37 UTC, Squirrel18 commented on action.yml
> +          git clone https://${{ inputs.access-token }}@github.com/Pearson-Advance/$repository.git \
We need to add the capability of cloning the projects from a specific branch. @sergivalero20

2023-03-01 15:29 UTC, sergivalero20 commented on action.yml
> +    default: 'false'
I tried to change it before, but I got this error: _**A string representing the default value. The default value is used when an input parameter isn't specified in a workflow file.**_. However I can change the default value to ''. @Jacatove

2023-03-01 16:04 UTC, sergivalero20 commented on action.yml
> +          git clone https://${{ inputs.access-token }}@github.com/Pearson-Advance/$repository.git \
Ok, got it.

2023-03-01 16:07 UTC, sergivalero20 commented on action.yml
> +          "$(tutor config printroot)/env/build/openedx/themes/myopenedxtheme"
I reviewed it and `open-release/juniper.stage` branch is the default branch @Jacatove 

![image](https://user-images.githubusercontent.com/73655023/222195727-3ebe7f0c-032b-436f-89bd-4d7fd88433af.png)

2023-03-01 20:27 UTC, sergivalero20 commented
@Squirrel18 @Jacatove I added better comments in the README file and in each input of the Composite Action.

2023-03-01 23:03 UTC, Squirrel18 commented on action.yml
> +          "$(tutor config printroot)/env/build/openedx/themes/myopenedxtheme"
We need to be able to change the branch, so it should be an additional parameter or attached to the themes repository URL. @sergivalero20

2023-03-01 23:30 UTC, sergivalero20 commented on action.yml
> +  extra-requirements:
The last commit already contains that change. @Squirrel18 thanks.

2023-03-02 02:14 UTC, anfbermudezme requested changes

2023-03-02 02:14 UTC, anfbermudezme commented on README.md
> +          access-token: ${{ secrets.GH_PAT }}
Could you please change the name to github-token to make it clearer?

2023-03-02 02:14 UTC, anfbermudezme commented on README.md
> +| access-token       | String   |      Yes     | Personal Access Token (PAT). If you have not configured it yet, enter in the follow link to see how create a PAT: https://docs.github.com/en/authentic
Same comment for change the name to github-token.

2023-03-02 22:17 UTC, sergivalero20 commented on README.md
> +          access-token: ${{ secrets.GH_PAT }}
Yes, sure!
Thanks @anfbermudezme

2023-03-03 03:24 UTC, Squirrel18 requested changes

2023-03-03 03:24 UTC, Squirrel18 commented on action.yml
> +  theme-repository:
This is a public repository, so I think we can include the full Github URL path. @sergivalero20

2023-03-03 03:36 UTC, sergivalero20 commented on action.yml
> +  theme-repository:
Sure!
Change applied @Squirrel18

2023-03-03 04:44 UTC, alexjmpb approved these changes

2023-03-03 11:02 UTC, anfbermudezme approved these changes

2023-03-03 12:49 UTC, Jacatove approved these changes

2023-03-08 22:03 UTC, Squirrel18 approved these changes

2023-03-08 22:52 UTC, anfbermudezme approved these changes

2023-03-08 23:05 UTC, merged