PADV 325 - Integrate the build process with ecommerce.
Pearson-Advance/tutor-build-image-action pull request #4
Opened 2023-03-08 04:13 UTC by alexjmpb

## Ticket

https://agile-jira.pearson.com/browse/PADV-325

## Description

Per requirements of PADV-325, it's necessary for the image build action to have the capability of enabling a plugin when it's going to be build. For this reason, this PR aims to provide of that function the image building action.

## Type of Change

- [x] Determine whether a plugin is the one to be built.
- [x] Install the corresponding plugin.
- [x] Enable the plugin and it's dependencies.
- [x] Save configuration so the corresponding Dockerfile can be created.

## How to test

- Create a new workflow action in another repository
- In that action use this action with `uses: Pearson-Advance/tutor-build-image-action@vue/PADV-325 `
- Pass the necessary inputs to build a plugin image

## Reviewers

- [ ] @Jacatove
- [ ] @Squirrel18
- [ ] @sergivalero20
- [ ] @anfbermudezme

2023-03-08 12:44 UTC, sergivalero20 commented on action.yml
> +        source venv/bin/activate
There is a step that already activate venv @alexjmpb

2023-03-08 12:48 UTC, sergivalero20 commented on action.yml
> +    default: false
@alexjmpb Do you use VS code as code editor? if so, could you please install a plugin called YAML to see if it appears an error message like this: **Incorrect type. Expected "string".**

2023-03-08 12:53 UTC, sergivalero20 commented
@alexjmpb what do you think about add the corresponding description for those new steps in README file?
If you want, you can add it after I merge #3

2023-03-08 13:36 UTC, alexjmpb commented on action.yml
> +        source venv/bin/activate
Yes what happens is that every time a new step involving a shell is executed it creates a new shell causing the venv to be deactivated. So it's necessary to activate the venv in every step we are going to use it.

2023-03-08 14:02 UTC, anfbermudezme commented on action.yml
> +        python -m pip install ${{ inputs.plugin-package }}==${{ inputs.tutor-version }}
What do you think about add `-e `?

```suggestion
        python -m pip install -e ${{ inputs.plugin-package }}==${{ inputs.tutor-version }}
```

2023-03-08 14:11 UTC, Jacatove requested changes

2023-03-08 14:11 UTC, Jacatove commented on action.yml
> +        python -m pip install ${{ inputs.plugin-package }}==${{ inputs.tutor-version }}
@anfbermudezme There is no value in adding that parameter. Plugin is not supposed to be editable during the action execution.

@alexjmpb  I wonder if the plugins version is sync with the tutor version, could you check that?. From what I have seen in sandbox we have this:

![image](https://user-images.githubusercontent.com/40271196/223734881-4d9f7653-e4c8-4a15-82db-00b4fbe52ff9.png)
Probably there is need to specify plugin version.

2023-03-08 14:15 UTC, alexjmpb commented on action.yml
> +    description: 'String cotaining the plugins required to be enabled separated by spaces.'
@anfbermudezme  Do you think it's enough with adding an example in the readme or should I also add it in this description

2023-03-08 14:21 UTC, alexjmpb commented on action.yml
> +        python -m pip install ${{ inputs.plugin-package }}==${{ inputs.tutor-version }}
@Jacatove  @anfbermudezme  @Squirrel18 Maybe it's worth to add it if the plugin is going to be installed from a cloned repo in tutor-plugins/, in that case I can add two optional parameters one with the repo to be cloned and the other that decides whether the plugin is in pypi or in tutor-plugins. What do you think?

2023-03-08 14:34 UTC, alexjmpb commented on action.yml
> +        python -m pip install ${{ inputs.plugin-package }}==${{ inputs.tutor-version }}
@Jacatove yes it is installing the corresponding versions. https://github.com/Pearson-Advance/ecommerce/actions/runs/4364302579/jobs/7631453523 there can be seen after the line 519. If I'm not wrong all tutor plugins with versions > 15 and < 16 work with tutor 15.0.0

2023-03-09 02:29 UTC, sergivalero20 commented on action.yml
> +        source venv/bin/activate
Yes, you're right!
I was able to test it out without venv and it failed. Thanks @alexjmpb.

2023-03-09 02:33 UTC, sergivalero20 commented
@alexjmpb FYI I already merged #3.

2023-03-10 15:31 UTC, Jacatove requested changes

2023-03-10 20:48 UTC, Jacatove approved these changes
LGTM. Could you please change the title of the PR? It is still valid to relate it to PADV 325, but the feature you've just added goes beyond eCommerce, so it needs a better title. @alexjmpb

2023-03-10 21:46 UTC, anfbermudezme approved these changes

2023-03-11 00:30 UTC, sergivalero20 commented on README.md
> +| plugins   | String     | JSON array string containing the information of the plugins desired to install. Example: '[{"plugin_name":"ecommerce","package_name":"tutor-ecommerce==15"},{"plugin_name":"
@alexjmpb Could you please adjust the description to the correct column? You're missing **Required** column.

![image](https://user-images.githubusercontent.com/73655023/224453196-3140b0aa-0c77-40d0-8b9a-0d51baf2f2a9.png)

2023-03-11 00:37 UTC, sergivalero20 commented on create_plugins_files.py
> +passed_plugins_list = json.loads(sys.argv[1])
@alexjmpb what do you think about change the way you receive this arguments?
For example, there is a python package called **click** that you can use for creating beautiful command line interfaces in a composable way with as little code as necessary. Also it allows to prevent wrong arguments. Please check it out [here](https://pypi.org/project/click/).

2023-03-13 15:10 UTC, alexjmpb commented on create_plugins_files.py
> +passed_plugins_list = json.loads(sys.argv[1])
Thanks, I'll take it a look

2023-03-14 13:37 UTC, sergivalero20 approved these changes

2023-03-14 14:49 UTC, Squirrel18 requested changes

2023-03-14 14:49 UTC, Squirrel18 commented on README.md
> +| plugin-names            | Array     |      No      | Array containing the GitHub sources urls of the plugins to install. Example: ("git+https://github.com/overhangio/tutor-ecommerce.git" "git+https
I think it could also contain the Pypi packages name, not just the GitHub URLs. @alexjmpb

2023-03-14 14:49 UTC, Squirrel18 commented on action.yml
> +  plugin-sources:
```suggestion
  tutor-plugin-sources:
```

2023-03-15 14:20 UTC, Squirrel18 requested changes

2023-03-15 14:20 UTC, Squirrel18 commented on README.md
> +| plugin-names            | Array     |      No      | Array containing the GitHub sources urls of the plugins to install. Example: ("git+https://github.com/overhangio/tutor-ecommerce.git" "git+https
Please mention the different sources from where packages can be installed, like Pypi. Also, there are two entries with the same name "plugin-names", please fix it. @alexjmpb

2023-03-15 22:04 UTC, Squirrel18 approved these changes

2023-03-17 17:24 UTC, merged