PADV-328 - Add the Tutor Pearson plugin to the Action.
Pearson-Advance/tutor-build-image-action pull request #5
Opened 2023-03-13 18:19 UTC by anfbermudezme

WIP.

2023-03-13 19:48 UTC, sergivalero20 commented on action.yml
> +        git clone -b https://${{ inputs.gh-access-token }}@github.com/Pearson-Advance/tutor-pearson-plugin.git \
@anfbermudezme Could you please specify the target branch? You're missing it!

2023-03-14 12:50 UTC, alexjmpb commented on action.yml
> +        git clone -b main https://${{ inputs.gh-access-token }}@github.com/Pearson-Advance/tutor-pearson-plugin.git \
What do you think of installing it using pip?

2023-03-14 14:22 UTC, anfbermudezme commented on action.yml
> +        git clone -b main https://${{ inputs.gh-access-token }}@github.com/Pearson-Advance/tutor-pearson-plugin.git \
It will fail, following [this](https://docs.tutor.overhang.io/dev.html)

![image](https://user-images.githubusercontent.com/30726391/225030742-92e0a9f1-ed7a-4d4a-9f2b-ce460c9317c8.png)

Apparently it's necessary build the image and the plugins and extra requirements will be installed. However the plugin has the `-e ` which means whatever change the image will take that. I have questions there, I hope solve this today.

2023-03-14 18:53 UTC, anfbermudezme commented on action.yml
> +        git clone -b main https://${{ inputs.gh-access-token }}@github.com/Pearson-Advance/tutor-pearson-plugin.git \
I will mark this conversation resolved since now it's clear to us the difference between tutor plugin and edx platform plugin.

2023-03-14 19:54 UTC, sergivalero20 commented on action.yml
> +    - if: ${{ inputs.install-tutor-plugins == 'true' }}
@anfbermudezme could you please define this input (install-tutor-plugins)? You're missing it!

2023-03-14 20:01 UTC, sergivalero20 commented on action.yml
> +        tutor_plugins_to_enable=${{ inputs.tutor-plugins-list }} # It is an array that contains the name of each tutor plugin to be enabled.
@anfbermudezme could you please define this input (tutor-plugins-list)?

2023-03-14 20:08 UTC, sergivalero20 commented on README.md
> +| install-tutor-pearson-plugin | Bool     | No  | A boolean value that indicates if It is necessary to install the private tutor-pearson-plugin.|
@anfbermudezme could you please check the name of this input? I'm not seeing it in the action file.

2023-03-14 20:15 UTC, sergivalero20 commented on README.md
> +| install-tutor-pearson-plugin | Bool     | No  | A boolean value that indicates if It is necessary to install the private tutor-pearson-plugin.|
@anfbermudezme could you please add the description for **tutor-plugins-to-enable**, **tutor-plugins-array** and **install-tutor-plugins**? You're defining as inputs in action file, but you're missing add the description for them.

2023-03-14 20:28 UTC, Squirrel18 commented
@anfbermudezme We should follow the same approach as: https://github.com/Pearson-Advance/tutor-build-image-action/pull/4 to install Tutor plugins. The only change is that we need to include the github_token.

2023-03-15 02:57 UTC, sergivalero20 approved these changes

2023-03-15 15:48 UTC, alexjmpb commented on action.yml
> +    - if: ${{ inputs.install-tutor-pearson-plugin == 'true' }}
In the acceptance criteria of the ticket mention the prevention that in case there's an error while enabling the plugin, the build should not continue. Do you think that also apply to when for whatever reason the plugin is not enabled?

2023-03-15 22:11 UTC, Squirrel18 requested changes

2023-03-15 22:11 UTC, Squirrel18 commented on action.yml
> +    description: 'Action secret variable to obtain the tutor pearson plugin URL from GitHub following
This is not a secret value, it is just an environment variable. @anfbermudezme It's also worth mentioning the expected format of this value.

2023-03-15 22:11 UTC, Squirrel18 commented on action.yml
> +      shell: bash
```suggestion
      name: Install the Tutor Pearson Plugin
      shell: bash
      run: |
        source venv/bin/activate
        function modify_tutor_pearson_plugin_url() {
          local tutor_plugin_url=$1
          local tutor_plugin_url_and_token=${url/GH_TOKEN/${{ inputs.gh-access-token }}}
          echo $tutor_plugin_url_and_token
        }
        URL=${{ inputs.tutor-pearson-plugin-url }}
        TUTOR_PLUGIN_URL=$(modify_tutor_pearson_plugin_url $URL)
        pip install $TUTOR_PLUGIN_URL
        tutor plugins enable pearson-plugin
```

2023-03-16 14:01 UTC, anfbermudezme commented on action.yml
> +    - if: ${{ inputs.install-tutor-pearson-plugin == 'true' }}
If an error occurs, either because the organization environment variable was not set correctly or the plugin has an error, the tutor plugins enable command will return an error and stop the action. Here is an example:

https://github.com/Pearson-Advance/edx-platform/actions/runs/4418655120/jobs/7746058627

2023-03-16 14:43 UTC, alexjmpb approved these changes

2023-03-16 15:39 UTC, Squirrel18 approved these changes

2023-03-16 16:01 UTC, merged