PADV-377 - Remove custom themes step from Workflow
Pearson-Advance/tutor-build-image-action pull request #6
Opened 2023-04-11 16:44 UTC by sergivalero20

## Ticket

https://agile-jira.pearson.com/browse/PADV-377

## Description

We have created patches for enable comprehensive theming in ecommerce. They are already included in [tutor pearson plugin](https://github.com/Pearson-Advance/tutor-pearson-plugin). So, It is necessary remove any step related to the clonation of custom themes repository in order to avoid redundancy.

## Changes Made

- [x] Remove unnecessary step in the workflow
- [x] Remove unnecessary inputs descriptions in README file

## Reviewers

- [ ] @Squirrel18
- [ ] @anfbermudezme 
- [ ] @alexjmpb

2023-04-13 12:37 UTC, sergivalero20 commented on action.yml
> +        tags: "${{ inputs.organization-name }}/${{ inputs.repository-name }}:${{ inputs.image-tag }}"
@alexjmpb Exactly right. That change has an impact in the other ones services. I changed it because I think is more intuitive and actually it represents the repository in Docker Hub. 

In any case, I asked to Daniel about this change to know if it is necessary.

2023-04-17 13:50 UTC, Squirrel18 requested changes

2023-04-17 13:50 UTC, Squirrel18 commented on action.yml
> +  tutor-pearson-plugin:
```suggestion
  tutor-pearson-plugin-name:
```

2023-04-17 16:41 UTC, Squirrel18 approved these changes

2023-04-17 18:27 UTC, anfbermudezme approved these changes

2023-04-17 20:05 UTC, alexjmpb approved these changes

2023-04-17 20:09 UTC, merged